---
engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
checks:
  file-lines:
    config:
      threshold: 5000
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 250
ratings:
  paths:
  - app/**
  - "**.js"
exclude_paths:
- config/
- migrations/
