---
language: node_js
node_js:
  - 8.11.2
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  postgresql: "9.6"
before_install:
  - npm --version
  - node --version
install:
  - npm install
before_script:
  - psql -c "CREATE DATABASE finance_test;" -U finance
  - psql -c "CREATE ROLE finance LOGIN PASSWORD 'finance';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE finance_test TO finance;" -U postgres
script:
  - npm test
